spring.application.name=backend

# DB configs
spring.datasource.url=${DATASOURCE_URL}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.defer-datasource-initialization=false
spring.sql.init.mode=never

# Flyway properties
spring.flyway.check-location=false
spring.flyway.group=true
spring.flyway..locations=classpath:/db/migration

# Redis Properties
spring.redis.host=${REDIS_HOST}
spring.redis.port=${REDIS_PORT}
spring.redis.username=${REDIS_USERNAME}
spring.redis.password=${REDIS_PASSWORD}
spring.redis.ssl=false
spring.redis.jedis.pool.max-active=${REDIS_CONNECTIONS_MAX:5}
spring.redis.jedis.pool.max-idle=${REDIS_CONNECTIONS_MAX_IDLE:1}
spring.redis.jedis.pool.min-idle=${REDIS_CONNECTIONS_MIN_IDLE:1}
spring.redis.jedis.pool.max-wait=${REDIS_CONNECTIONS_TIMEOUT:8500}

# SendGrid properties
sendgrid.key=${SENDGRID_API_KEY}
sendgrid.from-email=${SENDGRID_FROM_EMAIL}
sendgrid.otp-template-id=${SENDGRID_OTP_TEMPLATE_ID}


jwt.secret.key=${JWT_SECRET_TOKEN}
access.token.expiration.in.milli.secs=${ACCESS_TOKEN_EXPIRATION_IN_MILLI_SECS}
refresh.token.expiration.in.milli.secs=${REFRESH_TOKEN_EXPIRATION_IN_MILLI_SECS}
gcp.web.client.id=${GCP_WEB_CLIENT_ID}
