spring.application.name=backend

#DB configs
spring.datasource.url=${DATASOURCE_URL:jdbc:postgresql://localhost:5432/recursive_edu?user=postgres&password=admin}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.defer-datasource-initialization=false
spring.sql.init.mode=never

#Flyway properties
spring.flyway.check-location=false
spring.flyway.group=true
spring.flyway..locations=classpath:/db/migration


jwt.secret.key=${JWT_SECRET_TOKEN:3nA5a8iQxkD/Tbqp0hXzNh+Z0oEr7hIbvUABHYG6C7M=}
access.token.expiration.in.milli.secs=${ACCESS_TOKEN_EXPIRATION_IN_MILLI_SECS:900000}
refresh.token.expiration.in.milli.secs=${REFRESH_TOKEN_EXPIRATION_IN_MILLI_SECS:604800000}
