spring.application.name=backend

#DB configs
spring.datasource.url=jdbc:postgresql://localhost:5432/recursive_edu
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=none
spring.jpa.defer-datasource-initialization=false
spring.sql.init.mode=never

#Flyway properties
spring.flyway.check-location=false
spring.flyway.group=true
spring.flyway..locations=classpath:/db/migration


jwt.secret.key=${JWT_SECRET_TOKEN:A14&&djhjkhf}
access.token.expiration.in.milli.secs=${ACCESS_TOKEN_EXPIRATION_IN_MILLI_SECS:900000}
refresh.token.expiration.in.milli.secs=${REFRESH_TOKEN_EXPIRATION_IN_MILLI_SECS:604800000}
